# Available models
# google://gemini-3-pro-preview
# google://gemini-2.5-flash
# openai://gpt-4.1-mini
# openai://gpt-5-mini
# ollama://mistral-nemo:12b"
# ollama://gemma3:12b

[env]
_.file = { path = ".env", redact = true }
LOG_LEVEL = "debug"
CURL_VERBOSE = "false"
BLOG_REVIEW_LIMIT = "5"
MINIMUM_QUALITY_SCORE = "4.5"
OLLAMA_API_BASE_URL = "http://localhost:11434"
CONNECTION_TIMEOUT_SECONDS = "30"
OPERATION_TIMEOUT_SECONDS = "120"
WRITER_LLM = "google://gemini-2.5-flash"
EDITOR_LLM = "openai://gpt-4.1-mini"
SEO_LLM = "openai://gpt-4.1-mini"

[tasks.start]
run = "python cli.py"

[tasks.test]
run = "python -m unittest discover -s tests"

[tools]
python = "3.14.2"
